### ISSUE TITLE
Enable a ClassMentors class owner to create a task in a course that requires all members of the course to solve a SingPathFire problem.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#10]

**Comment by dinoboff** [comment]
Todo:
[x] Update challenges schema to either point to badge or to singpathfire problem
[x] Update task form to add a problem as a condition
[x] event progress verifier on client and backend to check to progress

**Comment by dinoboff** [comment]
It should done.

**Comment by SingaporeClouds** [comment]
How do users solve the problem from the ClassMentors page?

On Sun, Apr 19, 2015 at 9:31 AM, Damien Lebrun <notifications@github.com>
wrote:

> It should done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/10#issuecomment-94219660>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University

**Comment by dinoboff** [comment]
1. the user would click on a link of a challenge he didn't complete.
2. solve the problem / earn the badge
3. the system* checks the progress at some point and save it in the the firebase DB

*Right now:
- the backend check the progress of every user on each of the event they joined every 3 hours.
- the user client check the progress of the user when he joins the event. The firebase rules doesn't allow the user to save a task as completed if he doesn't have the badge showing as earned in its CM profile or the user problem solution showing as solved in singpath.

The user client could also check the user progress each time the user visit the event page.

Note: current the user progress check by the client doesn't try to get the user profile data (like which badge she/he earned) to get updated and relies on the automatic update every 3 hours.

**Comment by SingaporeClouds** [comment]
The architectural goal is to allow the free tier users to validate their
own badges, strings, and links and then allow class owners to revalidate
these task completions once the individuals have validated them. I haven't
converted all of these requirements in to specific issues yet. I've
described the architectural direction in the design document.

https://docs.google.com/document/d/1sKYEOcuYIY6Isx7YIxyGccbvZG4-5UTp4Lw-qiRtXBo/edit#bookmark=id.uexe1dqw5db4

GithubForking Architectural Goals
<https://docs.google.com/document/d/1sKYEOcuYIY6Isx7YIxyGccbvZG4-5UTp4Lw-qiRtXBo/edit#bookmark=id.uexe1dqw5db4>

On Mon, Apr 20, 2015 at 7:24 PM, Damien Lebrun <notifications@github.com>
wrote:

>
>    1. the user would click on a link of a challenge he didn't complete.
>    2. solve the problem / earn the badge
>    3. the system* checks the progress at some point and save it in the
>    the firebase DB
>
> *Right now:
>
>    - the backend check the progress of every user on each of the event
>    they joined every 3 hours.
>    - the user client check the progress of the user when he joins the
>    event. The firebase rules doesn't allow the user to save a task as
>    completed if he doesn't have the badge showing as earned in its CM profile
>    or the user problem solution showing as solved in singpath.
>
> The user client could also check the user progress each time the user
> visit the event page.
>
> Note: current the user progress check by the client doesn't try to get the
> user profile data (like which badge she/he earned) to get updated and
> relies on the automatic update every 3 hours.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/10#issuecomment-94427821>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University

**Comment by dinoboff** [comment]
Should be done.
