### ISSUE TITLE
Class name limits and editing

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#101]
Double the allowed length of class names so that users can publicly provide the password. 

Provide a way for users to edit the class name and password after classes have been created.

**Comment by dinoboff** [comment]
Work in progress...

**Comment by dinoboff** [comment]
deploying...

If you visit an event has a owner and click edit, the edit view has now form to edit the name, set a new password and update the options (show progress/link).

**Comment by dinoboff** [comment]
@SingaporeClouds and the title max length is now 60 char.
