### ISSUE TITLE
Only premium users can create classes

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#106]
Add a premium attribute to Chris and Damien and only allow premium users to create classes. For now, this can work just like the featured attribute on classes.

**Comment by SingaporeClouds** [comment]
No GUI support is needed for this. Just let me know where the attribute is on the user profiles that you are setting.

**Comment by dinoboff** [comment]
@deploying

Users are made premium by adding set to true:
- `classMentors/premiumUsers/$uid` e.g. https://singpath.firebaseio.com/classMentors/premiumUsers
- and `classMentors/userProfiles/$publicId/user/isPremium` e.g.: https://singpath.firebaseio.com/classMentors/userProfiles/cboesch/user/isPremium
