### ISSUE TITLE
Enable ClassMentors users to enter their CodeCombat Screen name on their profile page without going to a setup page.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#11]

**Comment by dinoboff** [comment]
Should work:
1. go to https://firebase-dev-dot-singpath-hd.appspot.com/classmentors/
2. login
3. click on profile

**Comment by SingaporeClouds** [comment]
As clarification, users will need to enter a link to "Solve" link tasks.
Users will need to earn a badge to solve badge tasks. The current solution
has the task creator creating a task and providing a link but no way for
users to submit a link as a solution.

If the task creator is providing a link, it is to point the users toward
more detail elsewhere such as in a Google Document.



On Tue, Apr 14, 2015 at 8:27 PM, Damien Lebrun <notifications@github.com>
wrote:

> Should work:
> 1. go to https://firebase-dev-dot-singpath-hd.appspot.com/classmentors/
> 2. login
> 3. click on profile
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/11#issuecomment-92792078>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University
