### ISSUE TITLE
Custom ranking for school events

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#114]
4 to 10 events will be created each year which will need to show the users' schools. No GUI support is needed to configure these events, but a parameter will need to be set on the event in Firebase somewhere to identify the event as a school event. For example: 

event.schoolEvent = true

When the GUI detects that an event is a school event, it will add 2 additional columns to the event ranking - one for the user's school name and one for the user's rank amongst users from the same school. These two additional columns will be placed between the user's name and total badges. 

The ranking table will be sortable by these two new columns allow all users to be listed by school in alphabetical order or by school Rank. Listing by school rank would show all of the 1st place ranked users from each school followed by the 2nd place ranked users from each school. 

For the September Ace of Coders events, we will rank by school rank to find the top 20 2nd ranked users from each school. These will be the users, along with their 1st place ranked schoolmates, invited to the live event. The assumption is that if the event ranking is first ranked by total badges by default and then manually by school rank, the top 20 2nd place users from each school will be listed in order of most badges right below all the 1st place users from each school.

**Comment by dinoboff** [comment]
What should I do with user without a school? should they be allowed to joined? Or put it in an "Other Category?

I assuming they shouldn't join.

**Comment by SingaporeClouds** [comment]
Ideally when someone tries to join a school event without a school they would get an error message that this event requires a school to be provided on the users profile and then provide the user with a link to edit their profile. If you can add that additional check to the registration process and provide clear feedback, then please try to do that. 

If a user joins a school event and then removes their school from their profile or a user joins an event without a school before the event becomes a schoolEvent, then their school will just be shows as "None" or "Please add school".
