### ISSUE TITLE
Percent completes for classes not updating as users make submissions

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#117]
![image](https://cloud.githubusercontent.com/assets/116418/8110253/cf05a60a-108d-11e5-9f82-dcfc8e5a62f8.png)

**Comment by dinoboff** [comment]
@SingaporeClouds It should be fixed. "% completed" is still derived by GUI from the participants progress on a task:
- the user had their read access given back to other participant progress
- the controller method calculating the rate has been updated to look for the progress at the correct place.
