### ISSUE TITLE
ClassMentors Challenges

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#119]
Event owners will be able to select a pre-defined ClassMentors problems to assign similar to how they assign SingPath problems, Code Combat levels, and Code School badges as challenges . 

Class Mentors problems will have pre-defined help links and instructions. In the future, they will also contain tests that can be used to validate user submissions. 

The first ClassMentors problems available to assign will all be in a single level called contributions. Event owners can select any of the problems in the contributions level to assign for their event participants to solve. 

PythonTutor links will be the first type of supported ClassMentors problems.

- [x] implement #120.
- [ ] Update the challenge forms to create challenge from those problems.

**Comment by dinoboff** [comment]
TODO:
- [ ] Add UI and rules to create new CM problem. A problem should have a name, a type (link problem or text response problem), and a help link and a description.
- [ ] Update the challenge forms to create challenge from those problems.


@SingaporeClouds Some questions:
- Should problems be part of groups like Singpath paths and levels?
- Should you still be able to create link and text response challenge without a predefined problem?
- Should the user profiles list the CM problems a student has completed and does a user get a challenge automatically completed if he completed the same problem in an other event?

**Comment by SingaporeClouds** [comment]
Closing. We will be focusing on features that provide automated feedback to users and/or facilitate live classroom management.
