### ISSUE TITLE
ClassMentors Contributions

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#120]
ClassMentors will have a new menu item below events and profile called "Contributions". 

The Contributions partial will allow users to contribute new ClassMentors problems that event owners can assign as challenges for their events. 

To contribute a ClassMentors problem, users will need to provide a PythonTutor link with starter code and instructions and then optionally provide pre-code, post-code, and expected output. When verifying link submissions, the PythonTutor verifier will add code above and below the user's code and then check that the last n lines of printed output for the user's solution matches the  n expected output lines for the problem.

Any new problems contributed  by users will appear in the ClassMentors problems contributions level and class owners will be able to select problems from that level when creating new challenges.

**Comment by dinoboff** [comment]
TODO:
- [ ] Add new PythonTutor challenge type. It require some optional pre-code, a post-code and expected output field.
- [ ] Add UI to create new CM problem. A problem should have a name, a type (eg: link problem, text response problem...), and a help link, a description and any new problem type required field.

@SingaporeClouds Some questions:
- Who can create and see those contribution?
- Should contribution be part of groups like Singpath paths and levels?
- Should you still be able to create link and text response challenge without a predefined contribution?
- Should the user profiles list the CM problems a student has completed and does a user get a challenge automatically completed if he completed the same problem in an other event?

**Comment by SingaporeClouds** [comment]
Any users can contribute new ClassMentors problems.

All ClassMentor problems will be divided in to levels. One of the levels will be called "Contributions". All newly created problems will initially be saved in to the contributions level. At some point, the admin will move problems out of the contributions level in to different levels. 

There will be adhoc link challenges that can be created that do not have tests. These are what were added in May 2015. Text challenges are another type of challenge that can be created that do not require links. The new type of challenge being added in late June 2015 is a ClassMentors Problem Challenge. ClassMentors Problem challenges are like SingPath problem challenges. Users will select a ClassMentors problem from a level and assign that problem. 

Solving ClassMentors problems will show up on a users profile just like SingPath problems are shown. 

Once a user solves a ClassMentors problem in any event, the ClassMentors problem will show up as solved just like SingPath problems do. Previously solved ClassMentors problems will automatically show up as completed if assigned again in another event.

**Comment by dinoboff** [comment]
How will the verifier work? will we use our own backend to run the code or PythonTutor has an API to the get the output?

**Comment by SingaporeClouds** [comment]
We will use the ClassMentors docker-based verifier to check contributed ClassMentors problems. My thought was to use the same verifier that will be used to verify submissions to ClassMentors problems that have been assigned as challenges. The verifier will decode the source code from the PythonTutors link and run it to check if the expected output matches the actual output.

**Comment by dinoboff** [comment]
I implemented the partials to:
- view and add CM problem level (TODO: edit level): http://www.classmentors.com/#/levels
- The most recent level accepting contribution is the level that will be linked in the side menu. http://www.classmentors.com/#/contributions (TODO: enable side menu link to contribution level)
- view problem list, view problem details and delete a problem (TODO: edit problem).

**Comment by SingaporeClouds** [comment]
Closing do to the decision to defer any running of code, executing of tests, and providing of test feedback to SingPath.
