### ISSUE TITLE
Ace of Coders static partial

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#121]
Add another left menu link below events, profile, and contribute. This link will say "Ace of Coders" and link to a new static partial that can be manually edited in Github. 

Add a vanity url that also takes visitors directly to this static partial. http://www.classmentors.com/#/ace-of-coders

Make this url the default landing page rather than http://www.classmentors.com/#/events. Users to type www.classmentors.com should eventually arrive at #/ace-of-coders

The static partial for Ace of Coders will have information for the Ace of Coders event that will take place in September 2015. The initial partial will have a link to a Youtube video with details on the event and on how to register. 

Below the event will be a hard coded ranking of how many schools have registered for the JC and Secondary categories of the Ace of Coders event.

Below the schools with at least 1 student registered we can list all of the remaining secondary schools with no registered students. These could load 50 at a time like the old version of the engagement platform supported.

**Comment by dinoboff** [comment]
@SingaporeClouds How do you want the list of registered and unregistered school to de hardcoded?
As HTML in the partials or as JS array in the controller?

If it's in the controller you can derive the list of remaining secondary schools.

**Comment by SingaporeClouds** [comment]
For simplicity, I was just asking for a static HTML page that I could edit quickly and redeploy without worrying too much about all the controllers and configuration. If the partial was just HTML, I thought that I could ask a student to update it as well. 

If we derive the remaining schools rather than hard code them, speed and resources would be the main concern. If this is going to be the landing page for a few weeks and lots of students and teachers are checking back, we would want the static parts of the page to load and render quickly and not consume too many Firebase connections. 

Since you already have a controller in place, I'd rather pull the information from Firebase than hard code it in the controller. Pulling cached or static information from a Firebase URL would be easier to update than the controller code. Let's try listing all the remaining JC schools and then 20 of the remaining secondary schools that have not registered yet for the respective event. We can see how quickly this loads and how much of a resource impact it makes. If we stay away from using connections and just fetch the .json data, we should be fine. It is ok if these tables at the bottom of the partial take a few more seconds to load after the static information at the top of the screen has appeared. 

The Ace-of-Coders partial should not require that users be logged in. So the list of registered users and their schools would need to be publicly accessible if we decide to pull the live data rather than publicly accessible cached data. 

If we start by just pulling the live registration data, we can always fall back to pulling the latests stats from a cached location somewhere in Firebase if things become to complex or too many fetches are needed. In this case, I would just need a button somewhere to push to update and POST back the latest stats. This would be less error prone and faster than me continually having to manually calculate and edit the static data in Firebase. 

The secondary school event is now called the "Junior" Ace of Coders category and the JC event is the "Senior" category. So these would be the events to check for the participating schools information. 

As of July 9th it looked as if: 
6 of 28 school are participating in the senior category
9 of 160 schools are participating in the junior category

We can also try calculating this information just above the missing schools tables since we will already be fetching the data and doing the calculations.

**Comment by dinoboff** [comment]
The controller is there just to set the name the view in the main page toolbar.

I was thinking we could just derive the list of school from the list of participants forgetting that was private info. It probably just easier to keep the partial simple.

Can you start editing it like that?
Will you need to deploy the changes yourself?

**Comment by SingaporeClouds** [comment]
I will start editing the partial as it is. I will probably design it to pull data from an adhoc object in Firebase so that I can update Firebase in order to update the data in the partial. Then everyone can pull the cached data from the Firebase object rather than every users having to rebuild the latest stats.
