### ISSUE TITLE
School Event sort by rank in school and then by overall badges

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#134]
The event ranking does not currently support a second rank order. Ideally, the sort function could keep track of the last sort and use this as the secondary sort order. This would allow you to sort by one column and then another. 

The specific need is to be able to have the event ranking for school events to sort by "Rank in School" followed by the secondary sort order of total badges. We need to be able to take a screenshot of the top 20 students who are the 2nd ranked students in their school. Currently if you sort by rank in school, the results will not be sorted by total badges as the secondary sort order. 

Being able to set a filter value on a column (Rank in school == 2) and then sorting by another column would achieve the same objective.

**Comment by dinoboff** [comment]
@SingaporeClouds The ranking table is using Angular builtin `orderBy` filter and Angular provides a `filter` filter. Adding a filter would be easier. than building might own `orderBy` filter.

**Comment by SingaporeClouds** [comment]
Whatever is easiest should be fine. We can also just assume that the secondary filter will always be totalBadges by default for now.  

criteria = "schoolRank"; // or whatever is clicked on. 
ng-repeat="user in users | orderBy:[criteria, 'totalBadges']"

**Comment by dinoboff** [comment]
That's right, orderBy can take an array. That's easy them.

**Comment by dinoboff** [comment]
I am deploying a fix, using the simple array of order key. Let me know if it work, especially regarding the secondary order direction: if the order is set to reverse it will be set to to reverse on both keys.

It should be ok for most columns except for those containing names.
