### ISSUE TITLE
Code Combat registration does not support spaces

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#136]
Remove url encoding escape characters when authenticating with Code Combat. Wizard names with spaces are still causing problems. "Master Control Program" would be an example that causes problems.

**Comment by dinoboff** [comment]
Problem might be happening at proxying the request to convert the the user name to a user id.

Run with the app engine dev server it works. But it fails with app engine proper.

**Comment by dinoboff** [comment]
@SingaporeClouds webapp2 router would url-decodes the url sent to proxy. On the dev server, httplib2 (via urllib2 I think) would urlencode it before sending the request but on app engine httplib2 via appengine urlfletch would not.

A fix has been deployed and it fixes this issue.
