### ISSUE TITLE
Allow event owners to remove paticipants

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#140]
If a user accidentally joins an event with the wrong account or joins an event that they should not have, the event owner should be able to eject user from the event. 

Users should be able to rejoin the event without losing their progress just as though they had left the event on their own and rejoined.

**Comment by dinoboff** [comment]
@SingaporeClouds Deploying fix. There should be a button next to each participant allowing you to remove them (after confirmation).
