### ISSUE TITLE
Functions in a list comprehension is not recognised for Python

### ISSUE THREAD

**Issue by blueset** [ChrisBoesch/singpathfire#146]
cc @dinoboff /docker-code-verifier

Functions in a list comprehension is not recognised for Python

Example: ([Link](http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1SLLAnZm-8vFpw3mp/problems/-Jo1SNzLkPhJNMQpKSz8/play))

## Test
```python
>>> buildString([4,5,3],'hi')
 '4hi5hi3'
>>> [buildString(t,s) for t in [range(5),range(0,8,2),['blue','red','green','yellow']] for s in "tyei\n\t "]
 ['0t1t2t3t4', '0y1y2y3y4', '0e1e2e3e4', '0i1i2i3i4', '0\n1\n2\n3\n4', '0\t1\t2\t3\t4', '0 1 2 3 4', '0t2t4t6', '0y2y4y6', '0e2e4e6', '0i2i4i6', '0\n2\n4\n6', '0\t2\t4\t6', '0 2 4 6', 'bluetredtgreentyellow', 'blueyredygreenyyellow', 'blueeredegreeneyellow', 'blueiredigreeniyellow', 'blue\nred\ngreen\nyellow', 'blue\tred\tgreen\tyellow', 'blue red green yellow']
```

## Solution
```python
def buildString (a,b):
    pass
```

## Error message
> name 'buildString' is not defined

## Questions with similar problem
* http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1SW-67bEcHGOSP6TA/problems/-Jo1SWA7B-zD-cGGvhq6/play
* http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1SW-67bEcHGOSP6TA/problems/-Jo1SWIpKn2eOUi_5i_l/play
* http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1SW-67bEcHGOSP6TA/problems/-Jo1SWX5qfWZESea6JlY/play
* http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1SW-67bEcHGOSP6TA/problems/-Jo1SWevgy8fmfLSJAmg/play
* http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1SW-67bEcHGOSP6TA/problems/-Jo1SWnvxlebIpPmMMXQ/play
* http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1SW-67bEcHGOSP6TA/problems/-Jo1SWwdX8c3WlfZGBH4/play

---
BTW, where should I report an issue about a wrongly stated question?

**Comment by SingaporeClouds** [comment]
Entering issues here will be fine. We will comment on the issue here and close it here once the issue is resolved.

**Comment by dinoboff** [comment]
I can reproduce the problem. That how how the verifier is implemented:
```
>>> solution = r"""def foo(x):
...   return x*2"""
>>> test = r'[foo(x) for x in [1,2]]'
>>> global_scope = {}
>>> local_scope = {}
>>> filename = '<string>'
>>> mode = 'exec'
>>> # Initiate scopes
... ast = compile('', filename, mode)
>>> exec(ast, global_scope, local_scope)
>>>
>>> # Run solution
... ast = compile(solution, filename, mode)
>>> exec(ast, global_scope, local_scope)
>>> print(local_scope.get('foo'))
<function foo at 0x10af09c80>
>>>
>>> # We would extract the code to run with the doctest module
... # Then run it
... eval(test, global_scope, local_scope)
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
NameError: name 'foo' is not defined
```

If we remove the local scope, it works:
```
>>> solution = r"""def foo(x):
...   return x*2"""
>>> test = r'[foo(x) for x in [1,2]]'
>>> global_scope = {}
>>> filename = '<string>'
>>> mode = 'exec'
>>> # Initiate scope
... ast = compile('', filename, mode)
>>> exec(ast, global_scope)
>>>
>>> # Run solution
... ast = compile(solution, filename, mode)
>>> exec(ast, global_scope)
>>> print(global_scope.get('foo'))
<function foo at 0x10783ac80>
>>>
>>> # We would extract the code to run with the doctest module.
... # Then run it
... eval(test, global_scope)
[2, 4]
```

I will fix the verifier and deploy a new one later today.

**Comment by dinoboff** [comment]
@blueset it should be fixed

**Comment by blueset** [comment]
Fixed. Thank you.
