### ISSUE TITLE
Question test with syntax error (Python/Level 7/Building a String)

### ISSUE THREAD

**Issue by blueset** [ChrisBoesch/singpathfire#148]
Question with syntax error:
[Python/Level 7/Building a String](http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1SLLAnZm-8vFpw3mp/problems/-Jo1SNhJKnkC0iPE04_Z/play)

## Error
```python
#7
>>> has_duplicates(range(5000)+[4999])
```
> unsupported operand type(s) for +: 'range' and 'list'

## Suggested edit
```python
#7
>>> has_duplicates(list(range(5000))+[4999])
```

**Comment by dinoboff** [comment]
Thanks, I will edit it.

**Comment by blueset** [comment]
Fixed. Thank you.
