### ISSUE TITLE
(Suspectly) Global variable recognition issue in function

### ISSUE THREAD

**Issue by blueset** [ChrisBoesch/singpathfire#151]
cc @dinoboff /docker-code-verifier

(Suspectly) Global variable recognition issue in lists
Tested in [Python/Level 9/Swap variables pythonic way](http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1S636OP4Y7aPSSV9N/problems/-Jo1S7kiX69qX_2CoPGu/play).

## Test
```python
>>> a=1
>>> b=2
>>> [a, b]
[1, 2]
>>> swap()
None
>>> [a, b]
[2, 1]
```

## Solution
```python
def swap():
    global a
    global b
    a, b = b, a
```

## Error 
> name 'b' is not defined
(Possibly happened in line # 4 of the solution where variables are swapped. Interpreted according to the way python runs `a, b = b, a`)

**Comment by dinoboff** [comment]
Fixed with the new verifier (deploying)

**Comment by dinoboff** [comment]
@blueset Should be fixed

**Comment by blueset** [comment]
Fixed. Thank you.
