### ISSUE TITLE
Challenge completions greater than 100%

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#153]
If a user leaves an event after completing a challenge, the percent complete still appears to include the departed player. This can lead to completions greater than 100%. 

![image](https://cloud.githubusercontent.com/assets/116418/9276374/18e30716-42d6-11e5-96c5-bb1578850ed0.png)

**Comment by dinoboff** [comment]
We keep user solutions after leave (in case we come). The routine counting solved solution is checking the user is still a participant.

**Comment by dinoboff** [comment]
@SingaporeClouds it's deployed and fixed.
