### ISSUE TITLE
Syntax error in question Python/Level 10/Deck Class

### ISSUE THREAD

**Issue by blueset** [ChrisBoesch/singpathfire#164]
### Related question
[Python/Level 10/Deck Class](http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1SZTsXi1syOPj2OR1/problems/-Jo1SaKo9VAgwhxz_us2/play)

### Desciption
In line 10 of test
```python
>>> b<>a and len(a)==len(b)
```

According to [Python 3 documentation on comparison operators](https://docs.python.org/3.5/library/stdtypes.html#comparisons), `<>` is no longer accepted as _not equal_, `!=` should be used instead.

### Suggested edit
In line 10 of test
```python
>>> b != a and len(a) == len(b)
```

**Comment by dinoboff** [comment]
@blueset It should be fixed.

**Comment by dinoboff** [comment]
Thanks
