### ISSUE TITLE
Unrecognised issue in question Python/Level 2/Python Math - Again?

### ISSUE THREAD

**Issue by blueset** [ChrisBoesch/singpathfire#167]
### Question related 
[Python/Level 2/Python Math - Again?](http://www.singpath.com/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jo1S8SjqcW0zdohNZBP/problems/-Jo1S9rNu9P7gaYOt5Ki/play)
#### Test
```python
>>> rice
 9223372036854775808L
```
#### Solution
```python
rice = 9223372036854775808
```

#### Error
```
invalid syntax (<string>, line 1)
```

**Comment by dinoboff** [comment]
Fixed thanks.

@SingaporeClouds that test might need to be looked at. Maybe the test should be made private (and the failure result).
