### ISSUE TITLE
Allow users to remove a service registration so that they can rejoin

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#169]
If a user wants to switch their Code Combat username for some reason, there should be a way to remove the current Code Combat registration and then re-register with another Code Combat username.

The key use case is that a user may be logged in as someone else from the same browser and accidentally register with someone else's code combat user name.

**Comment by dinoboff** [comment]
@SingaporeClouds there's now a remove button at the top right corner:

![service screenshot](https://dl.dropboxusercontent.com/u/83967/Screen%20Shot%202015-08-31%20at%2010.25.18.png)

**Comment by SingaporeClouds** [comment]
Very nice. This should be helpful.

On Mon, Aug 31, 2015 at 5:29 PM, Damien Lebrun <notifications@github.com>
wrote:

> @SingaporeClouds <https://github.com/SingaporeClouds> there's now a
> remove button at the top right corner:
>
> [image: service screenshot]
> <https://camo.githubusercontent.com/60449c2ce74d02a033f07460b52cac62a5bbaa2f/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f38333936372f53637265656e25323053686f74253230323031352d30382d3331253230617425323031302e32352e31382e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/169#issuecomment-136314040>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University
