### ISSUE TITLE
SingPath does not allow users to reset their solutions and resolve problems. 

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#176]
![image](https://cloud.githubusercontent.com/assets/116418/9606130/2851ac26-50f4-11e5-9e41-55ac649a0f3b.png)

**Comment by dinoboff** [comment]
@SingaporeClouds 
Once a problem is solved, the "run" button is replaced by a "try again" one.

The user solution is reset leaving only meta/history field.
