### ISSUE TITLE
Enable a ClassMentors owner to create a task that requires all registered users of the class to earn a specific Code Combat badge.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#19]

**Comment by dinoboff** [comment]
This is should work:

1. go to [ClassMentor](https://firebase-dev-dot-singpath-hd.appspot.com/classmentors/)
2. select an event you own or create one
3. click the edit button in the top menu
4. click the new challenge button in the top menu
5. select codeCombat as service
6. a new select input should appear; select a badge
7. fill the rest of the form and submit.

You should be to the event edit view.
