### ISSUE TITLE
Display the completion percentage of each student on the y-axis of the table

### ISSUE THREAD

**Issue by clarencenpy** [ChrisBoesch/singpathfire#190]

**Comment by SingaporeClouds** [comment]
What should this percentage show? Should is show the completion percentage of all available challenges or all challenges open for submission? 
Should it be a percentage or something like (3/5) (4/5), (7/7)
Could this be a column just to the right of the participant name?

**Comment by clarencenpy** [comment]
A useful thing to display could be the completion percentage of all challenges open for submission, something like (3/5 complete) would be sufficient! A column right beside the name of the participant could really be helpful when we are trying to identify students who have not completed many of the challenges.

One more suggestion, if we are able to sort based on number of incomplete challenges, that would be great.

**Comment by SingaporeClouds** [comment]
Closing due to duplicate issue.
