### ISSUE TITLE
Provide CM task creators with a list of free Code School badges to choose from when creating badge tasks.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#21]

**Comment by dinoboff** [comment]
We will need to create a list of badge like we do for code combat. Right not, it's building the list of badge the the profile of users (for code combat it getting it from the list in the python module, saved on firebase DB)

**Comment by dinoboff** [comment]
Except for the short list of badge, it working like the code combat exemple in #19

**Comment by SingaporeClouds** [comment]
Here are the 62 free Code School Badges to include in the dropdown  badge selector box for Code School tasks. 

Code School Enrollment
Completed Discover DevTools
Completed JavaScript Road Trip Part 1
Completed Rails for Zombies Redux
Completed Shaping up with Angular.js
Completed Try Git
Completed Try jQuery
Completed Try Objective-C
Completed Try R
Completed Try Ruby
Level 1 on Building Blocks of Express.js
Level 1 on Discover DevTools
Level 1 on Fundamentals of Design
Level 1 on Git Real
Level 1 on JavaScript Best Practices
Level 1 on JavaScript Road Trip Part 1
Level 1 on Journey into Mobile
Level 1 on Rails for Zombies Redux
Level 1 on Real-time Web with Node.js
Level 1 on Ruby Bits
Level 1 on Shaping up with Angular.js
Level 1 on Try iOS
Level 1 on Try jQuery
Level 1 on Try Objective-C
Level 1 on Try R
Level 1 on Try Ruby
Level 1 on Warming Up With Ember.js
Level 2 on Discover DevTools
Level 2 on JavaScript Road Trip Part 1
Level 2 on Rails for Zombies Redux
Level 2 on Shaping up with Angular.js
Level 2 on Try jQuery
Level 2 on Try Objective-C
Level 2 on Try R
Level 2 on Try Ruby
Level 3 on Discover DevTools
Level 3 on JavaScript Road Trip Part 1
Level 3 on Rails for Zombies Redux
Level 3 on Shaping up with Angular.js
Level 3 on Try jQuery
Level 3 on Try Objective-C
Level 3 on Try R
Level 3 on Try Ruby
Level 4 on Discover DevTools
Level 4 on Rails for Zombies Redux
Level 4 on Shaping up with Angular.js
Level 4 on Try jQuery
Level 4 on Try Objective-C
Level 4 on Try R
Level 4 on Try Ruby
Level 5 on Discover DevTools
Level 5 on Rails for Zombies Redux
Level 5 on Shaping up with Angular.js
Level 5 on Try jQuery
Level 5 on Try Objective-C
Level 5 on Try R
Level 5 on Try Ruby
Level 6 on Discover DevTools
Level 6 on Try R
Level 6 on Try Ruby
Level 7 on Discover DevTools
Level 7 on Try R

**Comment by dinoboff** [comment]
Should be done.
