### ISSUE TITLE
Correcting visibility and open/closed challenge bahavior. 

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#224]
A few weeks back, ClassMentors event owners lost the ability to see all the submitted urls for link challenges. In order to see student links, event owners currently have to make the participant solutions viewable by all participants. Event owners used to be able to see all submissions and links when "Show all participant solutions" was disabled. This should be fixed so that event owners can always see links even when the class can not. 

Also, there is no longer any way to leave a challenge viewable and closed. If you close a challenge, it makes it invisible. Sometimes event owners want to prevent participants from changing their submissions after the due date, but would still like for everyone to be able to see each other's submissions. This should be fixed so that closed challenges are still visible. 

Here is some clarification: 

Open - enable or disable the ability for students to submit or change submissions. 
Hide - make the challenge visible or hidden by students
Show all participant progress - let the class see who has submitted. 
Show all participant solutions - let the class see each other's links and text submissions. If this is disabled, students only see "Complete" for other students.

**Comment by dinoboff** [comment]
The fixes have been deployed. It should now work as expected.
