### ISSUE TITLE
The Submit Link does not go away for SingPath problems

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#233]
When you solve a SingPath problem in ClassMentors, the Submit Link button does not go way. It should be replaced with Complete or Solved once the problem has been solved in SingPath.

**Comment by dinoboff** [comment]
It behave likes 3rd parties services challenges, the user to click the update button.

It should monitor singpath profile instead.

**Comment by SingaporeClouds** [comment]
The issue is not with the data updates. The sorting is working. I can sort
by who has earned the badge. I just can not see the "Complete" for all the
participants who have earned a badge or solved a problem. So I believe that
the issue is the with the GUI visibility, not the data. The data must
already be there and be getting updated in order for the sorting to be
working and updating as people earn the badges.


On Thu, Jan 14, 2016 at 2:01 AM, Damien Lebrun <notifications@github.com>
wrote:

> It behave likes 3rd parties services challenges, the user to click the
> update button.
>
> It should monitor singpath profile instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/233#issuecomment-171380892>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University

**Comment by dinoboff** [comment]
That's issue #234 I am about to deploy both fixes.
