### ISSUE TITLE
Links should not be required when creating tasks

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#25]
Links are just optional if the task creator wants to provide a link to an external document with additional details for a link for the user to go to. When this link is provided, it should be the hyperlink for the title or by provided by the title (link)

**Comment by dinoboff** [comment]
So a task should provide a solve button and optional link for more details. Can we mark #34, #35 as duplicated as this one?

**Comment by SingaporeClouds** [comment]
I think there there is a lot of information that we are trying to request the user to submit and then display. I've updated the [class view mockup](https://docs.google.com/spreadsheets/d/1q7vol1KbxhNWphLMRbPeHF4bxAnt2NjPLTecI6Njz0o/edit#gid=844261498) to try and better communicate the intent. 

![image](https://cloud.githubusercontent.com/assets/116418/7245629/0b068880-e821-11e4-91cb-40000650a9a9.png)

**Comment by dinoboff** [comment]
Should be fixed
