### ISSUE TITLE
Enable the admin to add new problems

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#3]

**Comment by dinoboff** [comment]
Currently, anybody can create a path, and only the creator can can add level and problem to it.

Admins can be created and have read and write access to all the DB. There's no interface for it (it should be on the back end), but should need to set `/permissions/canReadAll/$userId` and `/permissions/canWriteAll/$userId` to true to make $userId and admin.

I can add same ACL for each applications and specific  part of an application.
