### ISSUE TITLE
Show edit button to enter or change the link for a link task.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#30]
For "provide a link" tasks, the user will need to paste in a link. Provide an edit button for the user to click and enter their link. Once they click the edit button, a text box will appear. The edit button will change to a Save button and will be besides the text box. Once the users presses save. The button will revert to be an Edit button which will be besides the hyperlinked link that the user provided.

**Comment by dinoboff** [comment]
@SingaporeClouds deployed
