### ISSUE TITLE
Allow the class owner to open and close tasks.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#31]
When tasks are open, users can try to complete them by providing links or checking for badges. When tasks are closed, the users in a class can not make submissions for the tasks.

**Comment by SingaporeClouds** [comment]
We probably can't prevent a user from updating their profiles and causing badge tasks to be shown as completed.  This is mainly to block users from submitting links, strings, and saying that they watched a video after the task has been closed.

**Comment by SingaporeClouds** [comment]
The other key use case for this feature is to allow the class owner to keep tasks private until the class owner is ready to share them with the class. The class owner might want to setup all of the tasks for an entire class but then only make them visible to the class once a live class meeting starts or  after a few live class sessions. So there are probably two settings for tasks. 

Visible to class - Yes/No

And then for link and watch YouTube tasks we would have. 

Open for submission - Yes/No

**Comment by dinoboff** [comment]
- If an event is opened, it should have an `openedAt` property holding the timestamps of the time it was opened.
- If it's closed, it has a `closedAt` property holding the timestamps of the time it was closed.
- when an event is closed/opened it add the timestamp of the previous state into the history property.

E.g.: https://singpath-play.firebaseio.com/classMentors/eventTasks/-JqgFLOEMj3n4_dDjWU3/-JqgH2FlZE9VWhfn8iuk

**Comment by dinoboff** [comment]
@SingaporeClouds It's deployed.
