### ISSUE TITLE
Track the last times that tasks are opened and closed.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#32]
The system will keep track of when tasks were opened and when they were closed. When tasks are opened or re-opened, the close time will be cleared.

**Comment by SingaporeClouds** [comment]
Initially,  we can just track when tasks are made visible or hidden. Open and closed will just be settings for  link tasks to specify when they are open for submissions and when they are not.

**Comment by dinoboff** [comment]
I am currently tracking when tasks get closed (and hidden) or when when get opened (and visible).

A task can be closed and visible?

**Comment by SingaporeClouds** [comment]
Yes. A task may be visible but no longer be accepting submissions. 

For example, a class owner could give a class 1 hour or 1 week to submit a link. After that hour, the class owner could close the task for submissions. Everyone could see the task and see which users have submitted a link, but they would no longer be able to submit a link or edit the links that they had submitted prior to the class being closed/frozen. 

Making tasks invisible/not shown allows a class owner to configure all the tasks for a class in advance. 

The Open/Closed setting allows the class owner to configure when users are allowed to submit links, submit text (What is your wizard name?, What should we call you?), mark tasks as completed (Yes I watched the video), etc.

So there are 3 main states that a task could be in. 
Non-visible and not accepting submissions/edits
Visible but not accepting submissions/edits
Visible and accepting submissions/edits

There could also be the non-visible but accepting submissions case, but I can't imagine ever using this case unless it was to allow the class owner to test a task somehow. So for now, we can just assume that hidden tasks will be closed for submissions or whatever is easiest for you to implement.

**Comment by dinoboff** [comment]
OK. Although it's called closed/open, what's implemented right now is hide/show. I will properly implement close/open next.

**Comment by dinoboff** [comment]
@SingaporeClouds What about badge task. If the user get the badge after the task is closed, should the task shows as completed or not?

**Comment by SingaporeClouds** [comment]
I thought about this, but was concerned that it might be too difficult to implement. 

In the ideal case, a user would need to earn the badge while the challenge was open for solving. If the class owner closes the challenge, they are signalling that they no longer want to accept submissions, otherwise they could just leave all the challenges open for solving forever. So if it is possible to not mark challenges as solved if the challenge is closed and the badge has been earned, then let's try that. 

There could event be a field that you set somewhere to identify that the badge has been earned but now while the challenge is opened. This could be used to signal "late" badge earnings. If the users opened the challenge and did a refresh, all the late's would be converted/upgraded to completed.

If it isn't to difficult to implement the logic so that challenges are only marked complete while the challenge is open, then let's do that.

The ranking should always count all the tracked badges and problems regardless of the class challenges.

**Comment by dinoboff** [comment]
It's should be trivial. I just need use the user list of completed task; if the user has not completed the task and the task is closed, just skip the completeness test.

**Comment by dinoboff** [comment]
@SingaporeClouds deploying...
