### ISSUE TITLE
In ClassMentors, there is no link provided for a registered user for a class to go solve the assigned SingPathFire problem.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#34]

**Comment by dinoboff** [comment]
There's should be a link (the event owner currently has to provide - need to be automatic)

**Comment by SingaporeClouds** [comment]
Agreed. The GUI should automatically provide links or buttons to allow users to enter strings or urls to solve string-providing or link providing tasks. For other tasks, there should be a button to allow users to check to see if a badge has been earned or a problem has been solved on 3rd party service like Code School, Code Combat, and SingPath. This button will run a manual check from the client's browser and update the user's status for the task. Individuals will have permission to update their own status for each task. The class owner will then re-run these checks to confirm submissions for confirmed submissions to tasks in their classes. These confirmation will be saved with class-owner permissions and be read-only for individual users. The server-side API, in any, only re-verifies task completions for premium tier class owners. These verification results are written with admin permissions and are readable by class owners and participants.

**Comment by dinoboff** [comment]
Should be fixed.
