### ISSUE TITLE
There is no button provided for a ClassMentors class participant to check to see if their CodeSchool or Code Combat badges have been earned.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#35]

**Comment by dinoboff** [comment]
Should be done.

**Comment by SingaporeClouds** [comment]
I don't see where a users can tell that their SingPath problem has been solved or their badge has been earned. My profile shows the badges earned and SingPath shows the the problems as solved, but hitting the refresh button on the ClassMentors class view does not show the problem as completed. 

![image](https://cloud.githubusercontent.com/assets/116418/7332317/5ec357a2-eb6c-11e4-8da6-8b830ca5ed8a.png)

**Comment by dinoboff** [comment]
Instead of start challenge, it should say "completed".

Once, #29 is implemented, instead of "completed", it will show a badge if it applies.

![completed screenshot](https://dl.dropboxusercontent.com/u/83967/chris/Screen%20Shot%202015-04-25%20at%2010.08.00.png)

**Comment by dinoboff** [comment]
ps: I had to delete references to code school badges (I had to change code school badge ID).

Check at https://firebase-dev-dot-singpath-hd.appspot.com/classmentors/#/profile/ that you have earned the badges.

Maybe I forgot to delete the code school related task and the reference the wrong id.

**Comment by SingaporeClouds** [comment]
I refreshed my badges and I don't see the "Completed" text yet for a SingPath problem that I solved and Code School badges that I have earned. 

I'm assuming that the refresh button will recheck all open tasks that have not yet been completed. When I click the button, the system does not find that I have earned the badges or solved the SingPath problem. 

![image](https://cloud.githubusercontent.com/assets/116418/7332420/da489f3c-eb70-11e4-83af-29e096e56229.png)

**Comment by dinoboff** [comment]
I deployed a fix.

I still need to write a test before sending a PR.

**Comment by SingaporeClouds** [comment]
Looks good. Thanks.

On Sat, Apr 25, 2015 at 6:24 PM, Damien Lebrun <notifications@github.com>
wrote:

> I deployed a fix.
>
> I still need to write a test before sending a PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/35#issuecomment-96174601>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University
