### ISSUE TITLE
Allow Class owners to create a "Provide a link" task requires users to submit a link. Providing a link to a public fork of a Github repo would be an example.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#36]

**Comment by dinoboff** [comment]
@SingaporeClouds 

Right task is attached to a service and optionally  attached to a badge on that service or to a problem if the service is Singpath.

If we create too many type of task, we should only allow the backend to verifier a task is completed; the [firebase rule](https://github.com/dinoboff/Singpath/blob/firebase/firebase-rules/rules.yaml#L485)* to check a task is completed is already complicated to read and maintain as it is.

*link to my clone of the private Singpath repository; you should be able to access it.

**Comment by SingaporeClouds** [comment]
The first priority is to make it all work to ensure that we are thinking
through all the needed features.

The next priority is to make it right. I have added more details on the
architectural goals for task complete checking to the project
specification. Eventually, the server-side code for class mentors should
only be checking for premium accounts. Other classes should have a way for
class owners to verify task completion on their own and save back the
results.

On Mon, Apr 20, 2015 at 7:44 PM, Damien Lebrun <notifications@github.com>
wrote:

> @SingaporeClouds <https://github.com/SingaporeClouds>
>
> Right task is attached to a service and optionally attached to a badge on
> that service or to a problem if the service is Singpath.
>
> If we create too many type of task, we should only allow the backend to
> verifier a task is completed; the firebase rule
> <https://github.com/dinoboff/Singpath/blob/firebase/firebase-rules/rules.yaml#L485>*
> to check a task is completed is already complicated to read and maintain as
> it is.
>
> *link to my clone of the private Singpath repository; you should be able
> to access it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/36#issuecomment-94430921>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University

**Comment by dinoboff** [comment]
Ok. The backend should only be used to proxy request to code school (and maybe code combat for the mentor to verifier profiles) and to run the code verifier.

**Comment by SingaporeClouds** [comment]
Yes. Architecturally, I'd like to develop Class Mentors so that all class
owner jobs and/or admin jobs could potentially be performed from browser
tabs where the admin or class owner is logged in. This approach helps to
illustrate RESTful applications with very minimal server-side logic.

I think that the CodeCombat API may work with JSONP, so class owners
wouldn't need a proxy.

A generic proxy API that only allows fetches from a few specific websites
might be needed. CodeSchool would be the first API that we could use the
proxy for. The downside of adding a proxy is that when someone forks the
repo and runs the code from another host, the proxy might not work unless
it accepted traffic from any website. So the proxy would need to be very
specific to limit potential abuse.

SingPathFIre only needs to work from SingPath.com and the Class Mentors
code base only has to integrate with SingPathFire when the ClassMentors
code is being hosted from ClassMentors.com. SingPathFire.com will not need
to integrate with everyone's ClassMentors forks. But yes, SingPath.com will
need the API's to launch of verifiers and process verification jobs queued
up on Firebase.


On Tue, Apr 21, 2015 at 5:58 PM, Damien Lebrun <notifications@github.com>
wrote:

> Ok. The backend should only be used to proxy request to code school (and
> maybe code combat for the mentor to verifier profiles) and to run the code
> verifier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/36#issuecomment-94726303>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University

**Comment by dinoboff** [comment]
I am not sure JSONP works for all codecombat request. It's working for the whoiam request, but not for the list of level:

http://codecombat.com/db/user/54daa69580ad9352053d3a3e/level.sessions?callback=angular.callbacks._6

**Comment by SingaporeClouds** [comment]
Ok. Whenever cross-site access is not allowed and JSONP is not supported, have the class owner validation process running from a browser tab use the proxy. Keep a list of all urls supported by the proxy somewhere so that we can talk to the service providers about the specifics. If the service providers add JSONP support for an API, we can stop using the proxy for that API. 

For users that fork and locally deploy the codebase, the proxy calls to their deployment will not work since they will not have the proxy API. Class owners running classes on forked deployments will not be able to validate badges earned on 3rd party sites unless they implement their own proxy. This should fail as gracefully as possible. 

On ClassMentors.com, we will support the proxy for all users and handle the class owner validation automatically for premium users.

**Comment by SingaporeClouds** [comment]
Regular expressions are too much complexity at this point. Simple string matching will be fine and can be done on the user's local system. 

For link tasks, we just need something very simple such as "Link will contain these strings". Then I can ask users to submit a string that contains "koding.io" or "github.io". 

The users should then be given clear feedback if their link does not adhere to the pattern. 
"Your link does not contain 'koding.io'. Please provide a link that contains this string."

**Comment by dinoboff** [comment]
Ok.

Note that the current implementation might be broken. I am fixing the rule.

**Comment by dinoboff** [comment]
It should be fixed
