### ISSUE TITLE
SingPath should provide better feedback while solutions are waiting to be solved. 

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#42]
Rather than just showing "waiting for result" and estimated time and countdown should be provided. This countdown could be based on the number of items in the verification queue and if the verifier is warming up for the first time versus alive and verifying solutions.

**Comment by SingaporeClouds** [comment]
A few users are reporting that SingPath is not working. I think that they are just seeing the verifier warming up for 60+ seconds for the first time and then assuming that SingPath is broken rather than waiting 60+ seconds for the verifier to respond.

Implement a way to provide better feedback to the SingPath users on how long it will take to verify their code when they are the first person to hit a "cold" verifier and/or if the verifier is currently warming up. 

The initial message can be something like "The free SingPath verifier is warming up. Your second verification will be much faster." 

A 60 second count timer can also be shown to help the users to be patient.

**Comment by dinoboff** [comment]
@SingaporeClouds It's now showing a message the verification server is not up and it might take a few minutes to start up.

I am not showing a timer for simplicity (not having to watch for the verification output to change). Let me know if you would like one anyway.
