### ISSUE TITLE
Provide users with a default collection of tests and passing code when they begin editing new problems. 

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#46]
It should be easier to edit provided tests and solution code than to have to go read up on how to create problems for different verifiers. Users should be able to just look at the example tests and passing solution code to understand how to write their own tests.

**Comment by SingaporeClouds** [comment]
We only need one example problem and set of tests for each Path to provide the problem editor with something to delete down from.

**Comment by dinoboff** [comment]
Related to singpath/verifier/issues/25

**Comment by dinoboff** [comment]
Note that I will deploy the the patch with the new java verifier, once I migrate the problems.
