### ISSUE TITLE
Add API support for the Code Combat authentication callback

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#48]

**Comment by dinoboff** [comment]
work in progress...

**Comment by dinoboff** [comment]
It should be implemented.

When the use click for the code combat for the user name/id lookup, she is sent to the new identification endpoint.

 On code combat she will given a link that send her back to the app. That callback link includes in the query path the code combat user name. When landing, the secret key is verified, the user name is converted to a user id and the details are saved.

Note that the request to convert the user name to a user id has be to use the backend proxy.

**Comment by SingaporeClouds** [comment]
Marking this as closed but opening another issues to address the problem of supporting Code Combat names containing spaces.
