### ISSUE TITLE
Enable logged in users to land on a problem ready to solve just by clicking on a link in to that problem.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#5]

**Comment by dinoboff** [comment]
It currently works:

https://firebase-dev-dot-singpath-hd.appspot.com/singpath/#/paths/-JltRrSkwdZ0IWUoxuLG/levels/-Jltu5YJeIeDusS3EoGW/problems/-Jlv4TwISTvoLZ3X0NVz/play

... but only if the user is logged in. If the user is not logged in, the view loading will be cancel; if the user just landed on the site, he will be sent to the home page.

It will be an issue once classmentor is split out.

TODO:
- [] let the problem view load even if the user is not logged in

**Comment by SingaporeClouds** [comment]
We should require users to login before viewing the problem. 
I'd like to see this deployed and working to ClassMentors.com (engagementplatform) before closing the issue.
