### ISSUE TITLE
The Code School badges are overlapping on the profile page. Prevent overlapping by resizing. 

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#54]
![image](https://cloud.githubusercontent.com/assets/116418/7511657/230b5be4-f4d9-11e4-93b7-db5af576109d.png)

**Comment by blueset** [comment]
Tried to fix this problem changing `row-height` to 3:4 ratio.

**Comment by blueset** [comment]
This should be fixed for now.
[Imgur](http://i.imgur.com/4L2qcD7.jpg)

**Comment by dinoboff** [comment]
Thanks.
