### ISSUE TITLE
Review school list

### ISSUE THREAD

**Issue by dinoboff** [ChrisBoesch/singpathfire#57]
@SingaporeClouds Can you check the [school list](https://github.com/dinoboff/singpathfire/blob/master/src/shared/components/schools/schools.js) for any missing one.

**Comment by SingaporeClouds** [comment]
This list doesn't have any of the secondary schools in it. You can see all
the secondary schools in this live page.

https://rawgit.com/ChrisBoesch/singpathfire/master/src/mockups/schoolStats.html

There is a javascript array in this HTML page with all the schools listed.

https://github.com/ChrisBoesch/singpathfire/blob/master/src/mockups/schoolStats.html




On Mon, May 11, 2015 at 3:23 AM, Damien Lebrun <notifications@github.com>
wrote:

> @SingaporeClouds <https://github.com/SingaporeClouds> Can you check the school
> list
> <https://github.com/dinoboff/singpathfire/blob/master/src/shared/components/schools/schools.js>
> for any missing one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/57>.
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University

**Comment by dinoboff** [comment]
Should be fix in #498d559
