### ISSUE TITLE
Automatically add links for badge tasks.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#63]
Links to the levels and problems should automatically be added for codeSchool, codeCombat, and SingPath problem tasks. 

A default name and description should also be provided that the user could then edit if needed.

**Comment by dinoboff** [comment]
What do you need? Currently the uses sees link named "Start challenge" (or provide link) when he hasn't completed a task.

I could had the problem description as a tooltip.

**Comment by SingaporeClouds** [comment]
This is working properly. I didn't realize that I could leave the help link box blank and that you would lookup the link for the solve now button. Looks good.
