### ISSUE TITLE
Add SingPath data to the profile page

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#65]
Users should be able to see a SingPath section below the CodeSchool and Code Combat sections on their profile. The SingPath section will show how many problems the users has completed on each path. 

Python         8 / 100
Javascript    5 / 100
Angularjs     2 / 50
Pandas        4 / 50

The users SingPath ID can be inferred from their current ClassMentors login. 

Pressing the sync button will pull the users latest SingPath stats into their ClassMentors profile. The intent is to treat SingPath similarly to CodeSchool and CodeCombat.

**Comment by dinoboff** [comment]
- [ ] show the number of the problem solved on problem pages.
- [ ] calculate total number of problem show it on the CM profile pages

**Comment by dinoboff** [comment]
@SingaporeClouds it should be fixed
