### ISSUE TITLE
All new classes should be hidden by default.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#70]
All classes will be "hidden" by default. Class owners will need to manually share a link to their classes. 

The admin will be able to make classes public so that they show up in the default list of open classes.

**Comment by dinoboff** [comment]
TODO:
- [x] fix my service warping calls to AngularFire objects.
- [x] add "featured" property to event.
- [ ] add page for user to find the event they created.
- [ ] add page for admin to mark an event as featured.

**Comment by dinoboff** [comment]
e.g. this event is featured:
https://singpath.firebaseio.com/classMentors/events/-JoaglCVVoy-oQIwYA_5
