### ISSUE TITLE
Do not let non-members view class progress

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#74]

**Comment by dinoboff** [comment]
TODO:
- [x] update view
- [ ] tighten up rules for progress data
- [ ] tighten up rules for task data

**Comment by dinoboff** [comment]
The last part requires a change in the schema: tasks need to be moved from /classMemtors/events/$eventId/tasks to /classMemtors/eventTasks/$eventId/.

I uploaded the necessary changes on the stage DB and backend:
http://dev.engagementplatform.appspot.com/

I will deployed to the production DB and backend once I have the migration ready.

**Comment by dinoboff** [comment]
@SingaporeClouds The task and user progress are now hidden. but the ranking is now hidden. I still have to make that public.

**Comment by SingaporeClouds** [comment]
I have changed my mind about making the rankings for classes public. Let's keeps this simpler until we have hand the chance to work through more of the important features.

For now, only class members and the class owner will be able to view the class progress or rankings.  People will need to join the class to view the rankings.

**Comment by dinoboff** [comment]
@SingaporeClouds I have the public ranking working (I still need to deploy it). Should I make it private?

**Comment by SingaporeClouds** [comment]
If you have it working, go ahead and push it. I was just agreeing to drop
the feature if the security was going to be too difficult. I was worried
that the security might not allow students to see and register for an
unlisted class.

Push what you have and I will take a look.

**Comment by dinoboff** [comment]
@SingaporeClouds It's been deployed
