### ISSUE TITLE
Created classes do not show up for owner.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#75]
Owners can not see their classes unless they are featured. Users should be able to see all  the classes that they have created and all the featured classes. The user should see their classes at the top so that they can navigate to them to get the url to share with others. Then the should see the featured classes below the classes that they own. 

Ideally, the user should also see the classes that they are registered for between the ones they own and the featured classes at the bottom of the class list.

**Comment by dinoboff** [comment]
Before see this issue, I added tabs to the event view: the 1st tab shows featured events, the 2nd one shows created events and the last one shows joined view.

@SingaporeClouds It's easy enough to create one list instead. Should I convert the 3 tabs to 1 list instead?

**Comment by SingaporeClouds** [comment]
Let's keep the tabs for now and get them working properly.

**Comment by dinoboff** [comment]
The event records are fine, user profiles need an update.

**Comment by dinoboff** [comment]
The user's profiles should be fixed now on the production DB
