### ISSUE TITLE
Enable classmentors users to view public courses

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#8]

**Comment by dinoboff** [comment]
todo:
- [ ] update schema to handle public event.
- [ ] update form to make event public/private.

@SingaporeClouds:
- Should it be editable? can the owner changes his mind later and switch an event to public / private?

**Comment by SingaporeClouds** [comment]
All classes (events) are password protected. If the class owner wants to
let anyone join the class, they can include the password in the class
description for others to copy and paste. Task lists require registration
and knowing the password. Viewing the badge rankings for each class do not
require class registration.

On Tue, Apr 14, 2015 at 8:39 PM, Damien Lebrun <notifications@github.com>
wrote:

> todo:
>
>    -  update schema to handle public event.
>    -  update form to make event public/private.
>
> @SingaporeClouds <https://github.com/SingaporeClouds>:
>
>    - Should it be editable? can the owner changes his mind later and
>    switch an event to public / private?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/8#issuecomment-92796890>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University
