### ISSUE TITLE
Code Combat username lookup problem when there is a space in the name.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#80]
I have 5 different users choose Code Combat user names with spaces in them. "Jane Doe", "John Almighty". When they use names with spaces, the Code Combat verification process will not work properly. 

If I has the users to change their Code Combat names to remove the spaces, the Class Mentors lookup process works correctly. 

Need to update the ClassMentor Code Combat lookup code to handle Code Combat user names containing spaces.

**Comment by dinoboff** [comment]
@SingaporeClouds it should be fixed
