### ISSUE TITLE
Tasks do not show after joining an event.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#81]
If you navigate to a class to join it, then enter the correct password, you will still see tasks tab enable, but when you click on it, the tasks will still not be shown. You have to refresh your browser to get the tasks to appear after joining. 

The tasks should be show once a user joins a class without requiring a browser refresh.

**Comment by dinoboff** [comment]
I will make view reload after joining/leaving event

**Comment by dinoboff** [comment]
@SingaporeClouds it should be fixed
