### ISSUE TITLE
Passed in SingPath problem gets lost during login.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#82]
If you click on a SingPath problem link from ClassMentors and you are not logged in to SingPath when you land on SingPath.com. You will be redirected to the SingPath paths page and the passed in problem will be lost.

Users should be able to login after being prompted and then be abel to continue attempting to solve the problem that they linked in to SingPath to solve.

**Comment by dinoboff** [comment]
A problem can only load if the user starts solving it, by if we can record the starting time. To record the starting time, the user has to be  logged in and has to have a profile (and to get a profile, the user needs a public id - shared with CM).

That's the reason the problem view can't be seen logged off. We should should instead let the view load even without the problem load and show a form to login or register. 

1. If a user is not logged in, . The user will a form to log in. Once logged in, the view reloads.
2 If the user is not registered (no public id set), the view will show the form to register. and reload once it's set.

**Comment by SingaporeClouds** [comment]
I agree. We should show the login screen when the login is the blocking issue and show the profile completion form if that is the blocking issue. We should do this for all deep linked screens that people might land on and need prior setup such as problems, classes, paths, levels, profiles, etc.
