### ISSUE TITLE
Users can not join a class until they complete their profile.

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#83]
A few users navigated to a class to try and join but did not see the "Join" button. We eventually debugged this to be related to the users not having completed filling our their profile and not having selected a screen name. 

When users navigate to a class link and have not completed their profile steps, redirect them to their profile to select a screen name. 

This should avoid the issue of users arriving at a class with no Join button to press.

**Comment by dinoboff** [comment]
We could do like the last problem PR... We should load the view but show the a form to register and then reload the view after registraction.

**Comment by SingaporeClouds** [comment]
Agreed.  

Most new classmentors users will arrive via class links that they will want to join and most singpath users will arrive at singpath for the first time via classmentors task links from their classes.

**Comment by dinoboff** [comment]
Work in progress...

**Comment by dinoboff** [comment]
@SingaporeClouds deploying
