### ISSUE TITLE
Freeze Task title and % complete column headers

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#86]
Once there are a large number of users, when you scroll down in the task table, you can no longer see the task title or percent complete. 

Make the top two table rows the task title and % complete. 
Freeze these header rows so that they remain visible as you scroll down to look at the data for users 45 to 50. 

Similarly, freeze the left-most name column so that as you scroll over to view tasks 25 to 30, you  will still be able to see the names of the users on the left. 

The individual user results will be the scrollable portion of the table.

**Comment by dinoboff** [comment]
I have seen it done but I am am sure how.

**Comment by dinoboff** [comment]
I think I know how will freeze the top row I am not sure I will freeze the the name column at the same time.

**Comment by SingaporeClouds** [comment]
The current implementation is working well.  I like the Material design approach. Ideally we will be able to find something that already implements all the requested grid features without too much work while still playing nice with material design. 

The column pinning example from ng-grid is what I have in mind. This example supports fixed/pinned columns, fixed header rows,  2-way sort by column header, and row striping. 

http://angular-ui.github.io/ng-grid/#/examples

ng-grid is being rewritten as UI Grid. Hopefully they have the material design concepts in mind as they are doing the rewrite. The column pinning example for ui-grid looks very robust. It even worked well on my phone.  Please take a look to see what you think. 

http://ui-grid.info/docs/#/tutorial/203_pinning

**Comment by SingaporeClouds** [comment]
As reference, it is currently very easy to get lost when scrolling down or across in an event with more than 10 challenges and 20 participants. I like the way that I can use 2 fingers on my Mac trackpad to quickly scroll down or over without having to page through results. However, it would be helpful to have the challenge tile row frozen and the participant name column on the left frozen. 

![image](https://cloud.githubusercontent.com/assets/116418/10123793/3ba58faa-6575-11e5-947c-7417beabd5b3.png)
