### ISSUE TITLE
Remind users to add Code Combat from the task table

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#88]
If the user has joined a class and the class has assigned a Code Combat badge task, remind the users to add their Code Combat name to their profile. Either direct them to the profile page or let the do the lookup directly from the class table,  which ever is easier.

**Comment by dinoboff** [comment]
@SingaporeClouds Deploying...

Probably when landing on the profile view, a message should pop saying why they were send to that page.

**Comment by SingaporeClouds** [comment]
Not every ClassMentors user will play Code Combat, but if a Code Combat challenge is given as part of a class, the user will need to authenticate with Code Combat. We just need to have an intuitive way for users to understand the Code Combat registration process once they've been assigned a Code Combat challenge to complete.
