### ISSUE TITLE
Enable a ClassMentors user to join a course by providing the course password

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#9]

**Comment by dinoboff** [comment]
Should work:
1. go to https://firebase-dev-dot-singpath-hd.appspot.com/classmentors/#/events
2. login
3. click "Test Event"
4. click "join"
5. enter "password" as password

**Comment by dinoboff** [comment]
@ChrisBoesch/owners  Should the password be entered to view the event?

**Comment by SingaporeClouds** [comment]
The password will be needed to join the class (event). Only registered
users for a class (event) should be able to see the list of tasks and who
has completed what.

Anyone will be able to view the badge rankings for classes. The badge
rankings can be public.

On Tue, Apr 14, 2015 at 8:32 PM, Damien Lebrun <notifications@github.com>
wrote:

> @ChrisBoesch/owners <https://github.com/orgs/ChrisBoesch/teams/owners>
> Should the password be entered to view the event?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisBoesch/singpathfire/issues/9#issuecomment-92794291>
> .
>



-- 
Best Regards,
Chris Boesch
Associate Professor of Information Systems (Education)
Singapore Management University
