### ISSUE TITLE
Delete task

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#91]
Add a button on the edit task page to allow Class  owners to delete a task.

**Comment by SingaporeClouds** [comment]
If it is easier, we can just archive tasks rather than delete them. The we don't have to worry about cleaning up all the references to the task. You could just set an archived=True attribute on the task and then have the GUI filter out and ignore all archived tasks. 

The same approach could be applied for classes, problems, and other content that has references that would be complex to clean up.

**Comment by dinoboff** [comment]
What would be the difference between archived and hidden? Once it's archived it doesn't show in the owner list of task he/she cane edit?

**Comment by SingaporeClouds** [comment]
We are using the term "hidden" when we talk about hiding events from class participants. Event owners can still see the hidden challenges to unhide them and open them. 

My recommendation, assuming it is the simpler option, is to allow users to archive events and challenges in events so that they will no longer show up in the GUI and the system won't have to go back and delete all the references to the items. Then the GUI could also have a simple check box that says "Show archived" to allow the users to see all their archived events and challenges in events.

**Comment by dinoboff** [comment]
@SingaporeClouds deploying

The PR only allow tasks to be archived by owners. Please open new issues if you want event to be archived or if users should be able archive event or task too.
