### ISSUE TITLE
Private and shared link tasks submissions

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#93]
When a class creator assigns a link task, they should have the option to make the class participant solutions public or private for the entire class. 

If submitted task links are public, everyone in the class will see the "Complete" message hyperlinked and be able to browse to see the each class participant's submitted link. 

If the task requires submitted task links to be private, the class participants will only see the non-hyperlinked "Complete" message as the current GUI provides.

**Comment by dinoboff** [comment]
It's not implemented. However it can currently only be set when creating the event.

When fixing #101 I will allow the option to show link to be editable.

**Comment by dinoboff** [comment]
@SingaporeClouds What is currently deployed is an option to make all task completeness and link url public / private.

Do you need to option to be by task instead?

**Comment by SingaporeClouds** [comment]
I'd like the option for the "Completed" text for individual challenges to be configurable so that it will ether be hyperlinked to the users' submitted links or it will not be hyperlinked. 

Event participants will either be able to click and view each others' submissions, or they will just see the word completed. The event owner should be able to turn the option on and off. 

Links should open in another chrome tab rather than redirect the user.

**Comment by dinoboff** [comment]
@SingaporeClouds  it's currently an event option. I going to make it a task option.

Should I remove the event option? make it the default option for new task? a way to switch all existing task options at once?

**Comment by SingaporeClouds** [comment]
Sharing challenge links with the rest of the class should be a challenge option. The default should be to not share and to just show "Complete" instead. 

I can't foresee needing and event-wide option to change all challenges to share links. So you can remove or hide that option.

**Comment by dinoboff** [comment]
@SingaporeClouds 

Actually, I can have the GUI hide/show the solution and progress of each participants but creating the  firebase rule is a little more problematic.

If each solution and progress have their its own access settings, I can't just request the progress and solution for all task of an event, e.g.: https://singpath.firebaseio.com/classMentors/eventProgress/-JoaglCVVoy-oQIwYA_5 .

I would need to send a request for each tasks allowing viewing progress and for each participants. For solution it wouldn't be as bad. I could delay requesting a user solution until the user click on the link but it wouldn't be a simple link showing the url when the cursor is hover it.

What I could do is mirror the data accessible to other participant in `classMentors/eventProgress/$eventId` and `classMentors/eventSolutions/$evenId` into two other path, like `classMentors/eventPublicProgress/$eventId` and `classMentors/eventPublicSolutions/$evenId`. It would get updated each time the progress is updated or each time a task option is switch.

**Comment by SingaporeClouds** [comment]
Let's just keep this as simple as possible. Keep the realtime updates working and just hide and show the tasks and links to submissions based on the configured settings.

I agree that a rule to API protect links would be more complex. The protected submission links would need a different rule than the record that something was submitted.

If I really want to API protect submitted links from other class members in the future, I may need to give up all visibility by other users in the class, but even then the class owner could still read the submissions.

**Comment by dinoboff** [comment]
About the access control change to hide the data at a task level instead of the event level:
- the rules is easy enough to write. Right now the read rule is defined at at `classMentors/eventProgress/$eventId`. It would just need to be defined at `classMentors/eventProgress/$eventId/$userPublicId/$taskId`. Same for link solution data.
- It doesn't affect how we will get the data to get updates; it will still use angularfire object and have realtime update.
- What will change once I implement the new rules is that participants can't read `classMentors/eventProgress/$eventId` anymore (1 angularfire object to get event progress of all participants), they will only be able to read `classMentors/eventProgress/$eventId/$userPublicId/$taskId` (`nP * nT` angularfire objects where nP is number of participants and nT the number of tasks allowing progress read). I am affraid it won't scale but I might be wrong.

Edit: there's a solution. Changing the schema to `classMentors/eventProgress/$eventId/$taskId/$userPublicId` would help reading other participants progress at the cost reading one participant own progress - a good trade off. For each task allowing "public" access to progress, create an angularfire to `classMentors/eventProgress/$eventId/$taskId` and for other tasks and the participant own progress, create an angularfire object to `classMentors/eventProgress/$eventId/$taskId/participantId`.
Also grouping showing progress and solution in one option would help.

**Comment by SingaporeClouds** [comment]
This doesn't seem worth it to me as a understand it. It still seems like it would be less bandwidth and faster to allow the user to access. 
classMentors/eventProgress/$eventId

and fetch the entire list of tasks and progress at once rather than have them fetch one task at a time. I think that you should be able to just have the GUI hide the challenges for the vast majority of use cases. 

Then the users would just have to watch for changes in a single object, the event object. 

There are 2 main use cases to keep in mind as we consider future performance and scalability. Most events will just have 20 to 40 members that meet for about 3 hours at a time. During those live sessions, the realtime update and feedback are what are most important. 

There will be 4 to 8 events per year where there could be 100 to 200 participants. For those events, badge updates will matter, but the challenge updates won't really need to be realtime. I don't know if it makes sense to gracefully degrade away from the realtime feature or to just keep the logic as simple and consistent as possible. It could also be that we might choose to only show 40 participants at once in the challenge table view to limit the need for lots of connections. 

We could also look at ways of only using the realtime update feature for open challenges and then for closed challenges we could do a simple JSON GET when the event is viewed for the first time and show all the static challenge information. Then we could do live updates just for the open challenges.  However, I don't think that Firebase will care if we are watching a single challenge or the entire event. Either will count as a connection. 

Please use your best judgement. We don't have to optimize too soon. The 200 live connection limit is the most expensive resource to manage. We shouldn't have a problem with that for a while. Just think about how we might switch between realtime Firebase objects that use connections to simple JSON GET's at some point if we needed to.  We can also keep in mind how to limit the number of Firebase connections to 1 for any given user. The event challenge view maybe the only thing that needs to be real time if the event ranking is reloaded each time the tab is accessed.

**Comment by dinoboff** [comment]
@SingaporeClouds deploying

To the option to show/hide other participant progress / solution on a task have been added.

The rules allow users to access other participants progress and solutions but the ui hide them.
