### ISSUE TITLE
Users still appear in class rankings after leaving classes

### ISSUE THREAD

**Issue by SingaporeClouds** [ChrisBoesch/singpathfire#99]

**Comment by dinoboff** [comment]
@SingaporeClouds Do they stay after updating the event progress and ranking?

**Comment by SingaporeClouds** [comment]
Yes. For example, Chris Boesch is in the class ranking for this class but
has left the class and not rejoined.

http://www.classmentors.com/#/events/-JppMqyKGg_ivZHotKwK

**Comment by dinoboff** [comment]
That's right, the progress update only update the progress (and ranking) of each participants one at a time. It doesn't reset the ranking list itself. The ranking data of a user should be removed when he leaves.

I will update the service removing a participant and update the rules to allow user to remove his own ranking data.

**Comment by dinoboff** [comment]
The fix only apply to participants leaving after the patch deployment. I still need to fix corrupt ranking.
